### PR TITLE
Bump Lightning Charge version to 0.3.9

### PR DESCRIPTION
**Pull request by danielalexiuc**

### CODE REVIEW

**Comment by NicolasDorier** [comment]
have you check it still work?

**Comment by danielalexiuc** [comment]
I'll fork this and test it out. How does it work - If I update the version here, and then run lightning-update.sh in lighting-charge-azure, will it pick it up automatically and update lightning charge? Or will I need to create a new release version of lighning-charge-azure as well?

**Comment by NicolasDorier** [comment]
I think if you properly set the wizard to point your repo it is fine.

However may I ask you why you are interested into this repo? Because if you just want to play with clightning then you can try btcpayserver. It also install CLightning.

**Comment by danielalexiuc** [comment]
Thanks, I'll give it a try.

**Comment by danielalexiuc** [comment]
Ok I cloned my repository into /var/lib/waagent/custom-script/download/0 (backing up the existing lightning-charge-docker directory).

Then ran lightning-update.sh

It successfully upgraded to 0.3.9, and restarted successfully. I am now using it in production. I think this repository is worth keeping up to date. Lightning Charge has a nicer API than BTCPayServer for somebody who wants to run it headless - for now anyway :)

**Pull request merged**
